### ISSUE TITLE
Support packed-refs

### ISSUE THREAD

**Issue by josharian** [speedata/gogit#10]
Refs can be recorded in the `packed-refs` file. gogit doesn't look there, which causes it to be unable to open my repo.

The README says the project is "not really actively maintained". Is a PR adding support for this likely to be reviewed? If not, I'll just use git2go...but I'd rather have pure Go if I can arrange it.

**Comment by pgundlach** [comment]
There is some support for `packed-refs`, as far as I remember. It might be outdated somehow. 

A patch / pull request with a test is very welcome!

**Comment by pgundlach** [comment]
Thank you _very much_ for the patch!

**Comment by josharian** [comment]
Thanks for the speedy merge/review. :) Now that I know there's someone paying attention on the other end, I may send more.
