### ISSUE TITLE
How to lookup HEAD^1 etc

### ISSUE THREAD

**Issue by JamesMilnerUK** [speedata/gogit#14]
Firstly thanks for the super library. Just having an issue with accessing previous commits. For example:

```go
	ref, err := repository.LookupReference("HEAD^2")
	if err != nil {
		log.Fatal(err)
	}
```

Will cause 

`ref not found`

Even when HEAD^2 exists. Any idea how to achieve this? Or to list through all the previous commits of a reference?

**Comment by pgundlach** [comment]
HEAD^1 and similar refs are currently not supported. You can use [`func (ci *Commit) Parent(n int) *Commit`](https://godoc.org/github.com/speedata/gogit#Commit.Parent) to get the first, second, ... parent and [`func (ci *Commit) ParentCount() int`](https://godoc.org/github.com/speedata/gogit#Commit.ParentCount) to get the number of parents available.

If this does not solve the problem, please re-open the ticket with some info.

**Comment by JamesMilnerUK** [comment]
That works, thank you
