### ISSUE TITLE
Why LookupCommit method loads tree object?

### ISSUE THREAD

**Issue by vitaliel** [speedata/gogit#3]
In [commit.go](https://github.com/speedata/gogit/blob/master/commit.go#L135) when  commit object is loaded from repository, method also load the tree object.

What was the concern of doing so?

It generates additional useless overheat when collecting a commit list.

Can we modify the method to avoid usage of parseTreeData?

**Comment by pgundlach** [comment]
I guess the 14 days are now over... You are right, that the tree object is not necessary in  `LookupCommit()`, but there are applications out there that use the tree object. So it is a design flaw that I can't fix (without breaking existing code).
